# Generated by Django 2.2.3 on 2019-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tranporter_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Photograph', models.ImageField(blank=True, upload_to='transporter/%y/%m/%d')),
                ('Vehicle_Number', models.CharField(max_length=20)),
                ('License_Number', models.CharField(max_length=20)),
            ],
        ),
    ]
